"""updateJobDomain

Revision ID: 0d2dc3f87414
Revises: 1fda627944ff
Create Date: 2020-12-18 19:37:47.328533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2dc3f87414'
down_revision = '1fda627944ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_domains', sa.Column('alternative_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_domains', 'alternative_name')
    # ### end Alembic commands ###
