"""removeJobPostDetail

Revision ID: 10eef52ed444
Revises: c1c6999b5862
Create Date: 2020-12-20 04:53:07.362682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10eef52ed444'
down_revision = 'c1c6999b5862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('deadline', sa.DateTime(), nullable=False))
    op.add_column('job_posts', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('job_posts', sa.Column('job_title', sa.String(length=200), nullable=False))
    op.add_column('job_posts', sa.Column('last_edit', sa.DateTime(), nullable=False))
    op.add_column('job_posts', sa.Column('max_salary', sa.Float(), nullable=True))
    op.add_column('job_posts', sa.Column('min_salary', sa.Float(), nullable=True))
    op.add_column('job_posts', sa.Column('posted_in', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'posted_in')
    op.drop_column('job_posts', 'min_salary')
    op.drop_column('job_posts', 'max_salary')
    op.drop_column('job_posts', 'last_edit')
    op.drop_column('job_posts', 'job_title')
    op.drop_column('job_posts', 'is_active')
    op.drop_column('job_posts', 'deadline')
    # ### end Alembic commands ###
