"""addJobPostModel

Revision ID: 15caaee8299b
Revises: 7b098aa43e03
Create Date: 2020-12-17 23:49:27.851337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15caaee8299b'
down_revision = '7b098aa43e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('job_domain_id', sa.Integer(), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('requirement_text', sa.Text(), nullable=True),
    sa.Column('benefit_text', sa.Text(), nullable=True),
    sa.Column('technical_skills', sa.String(length=500), nullable=True),
    sa.Column('soft_skills', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['job_domain_id'], ['job_domains.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_posts')
    op.drop_table('job_domains')
    # ### end Alembic commands ###
