"""updatetablecv1

Revision ID: 18ac593ad2b3
Revises: 2aaf0a65a53d
Create Date: 2020-12-26 18:21:03.991734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ac593ad2b3'
down_revision = '2aaf0a65a53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('dump', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'dump')
    # ### end Alembic commands ###
