"""updatesavetables

Revision ID: 2617a20a8227
Revises: 24ecd7326544
Create Date: 2021-01-03 00:07:08.069077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2617a20a8227'
down_revision = '24ecd7326544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cand_job_saves', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('cand_job_saves', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('recruiter_resume_saves', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('recruiter_resume_saves', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiter_resume_saves', 'updated_on')
    op.drop_column('recruiter_resume_saves', 'created_on')
    op.drop_column('cand_job_saves', 'updated_on')
    op.drop_column('cand_job_saves', 'created_on')
    # ### end Alembic commands ###
