"""updateresumetable

Revision ID: 2aaf0a65a53d
Revises: 51db38093b2b
Create Date: 2020-12-26 18:11:13.644231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aaf0a65a53d'
down_revision = '51db38093b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('educations', sa.String(length=10000), nullable=True))
    op.add_column('resumes', sa.Column('experiences', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'experiences')
    op.drop_column('resumes', 'educations')
    # ### end Alembic commands ###
