"""updateProvinceId

Revision ID: 32836839317c
Revises: fda51c3f062d
Create Date: 2020-12-28 22:50:19.965058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32836839317c'
down_revision = 'fda51c3f062d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('province_id', sa.Integer(), nullable=True))
    op.add_column('job_posts', sa.Column('province_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'province_id')
    op.drop_column('candidates', 'province_id')
    # ### end Alembic commands ###
