"""updateResumeModel

Revision ID: 380959e83b36
Revises: e06f01aec0ea
Create Date: 2020-12-27 15:01:50.335346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '380959e83b36'
down_revision = 'e06f01aec0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('job_domain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resumes', 'job_domains', ['job_domain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'job_domain_id')
    # ### end Alembic commands ###
