"""updateResume

Revision ID: 4ab9938291c2
Revises: 7fadaabdf2b3
Create Date: 2021-01-09 03:26:21.766573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab9938291c2'
down_revision = '7fadaabdf2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('download_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'download_url')
    # ### end Alembic commands ###
