"""updateContractType

Revision ID: 51db38093b2b
Revises: 10eef52ed444
Create Date: 2020-12-20 05:25:28.508989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51db38093b2b'
down_revision = '10eef52ed444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('job_posts', sa.Column('closed_in', sa.DateTime(), nullable=True))
    op.add_column('job_posts', sa.Column('contract_type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'contract_type')
    op.drop_column('job_posts', 'closed_in')
    op.drop_column('job_posts', 'amount')
    # ### end Alembic commands ###
