"""updateJPDetail

Revision ID: 6db8da2c90b6
Revises: 5facbee86f37
Create Date: 2020-12-18 02:25:13.745567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6db8da2c90b6'
down_revision = '5facbee86f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_post_detail', 'closed_in',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_post_detail', 'closed_in',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
