"""updateCompanyModel

Revision ID: 6efeb46c4889
Revises: 51db38093b2b
Create Date: 2020-12-25 14:21:26.386393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6efeb46c4889'
down_revision = '51db38093b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('background', sa.String(length=255), nullable=True))
    op.drop_column('companies', 'acronym')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('acronym', mysql.VARCHAR(collation='utf8_unicode_ci', length=80), nullable=True))
    op.drop_column('companies', 'background')
    # ### end Alembic commands ###
