"""AddNewTablesForSaveFeatures

Revision ID: 7b4e03ff2c23
Revises: f416dce3cd1a
Create Date: 2021-01-02 16:24:04.192830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4e03ff2c23'
down_revision = 'f416dce3cd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cand_job_saves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cand_id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cand_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiter_resume_saves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruiter_resume_saves')
    op.drop_table('cand_job_saves')
    # ### end Alembic commands ###
