"""updatetablecv2

Revision ID: 855cea9348ca
Revises: 18ac593ad2b3
Create Date: 2020-12-26 18:22:31.984857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '855cea9348ca'
down_revision = '18ac593ad2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'dump')
    op.drop_column('resumes', 'educations')
    op.drop_column('resumes', 'experiences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('experiences', mysql.VARCHAR(length=1000), nullable=True))
    op.add_column('resumes', sa.Column('educations', mysql.VARCHAR(length=10000), nullable=True))
    op.add_column('resumes', sa.Column('dump', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
