"""updatesubmissiontable

Revision ID: 9fc478e3c7e8
Revises: 32836839317c
Create Date: 2020-12-28 23:45:11.728402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc478e3c7e8'
down_revision = '80a57a4f1bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_resume_submissions', sa.Column('process_status', sa.Boolean(), nullable=True))
    op.add_column('job_resume_submissions', sa.Column('score_array', sa.String(length=100), nullable=True))
    op.add_column('job_resume_submissions', sa.Column('score_explanation_array', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_resume_submissions', 'score_explanation_array')
    op.drop_column('job_resume_submissions', 'score_array')
    op.drop_column('job_resume_submissions', 'process_status')
    # ### end Alembic commands ###
