"""Migration-Message

Revision ID: b37f89082ad4
Revises: dc8e747eba0a
Create Date: 2020-11-12 11:13:15.391651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37f89082ad4'
down_revision = 'dc8e747eba0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###
