"""Migration-Message

Revision ID: b4a3c618a660
Revises: b37f89082ad4
Create Date: 2020-11-13 18:04:53.842339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a3c618a660'
down_revision = 'b37f89082ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed_on')
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
