"""addGraphToJobPost

Revision ID: c5dfd805205e
Revises: 380959e83b36
Create Date: 2020-12-27 15:20:52.859939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5dfd805205e'
down_revision = '380959e83b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('domain_skill_graph', sa.Text(), nullable=True))
    op.add_column('job_posts', sa.Column('skill_graph', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'skill_graph')
    op.drop_column('job_posts', 'domain_skill_graph')
    # ### end Alembic commands ###
