"""addEducation

Revision ID: daf0da8c54c9
Revises: 2617a20a8227
Create Date: 2021-01-04 23:53:12.185647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'daf0da8c54c9'
down_revision = '2617a20a8227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('majors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('activity_details')
    op.drop_table('activities')
    op.drop_table('activity_parameters')
    op.drop_table('activity_types')
    op.add_column('job_posts', sa.Column('education_level', sa.Integer(), nullable=False))
    op.add_column('job_posts', sa.Column('majors', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'majors')
    op.drop_column('job_posts', 'education_level')
    op.create_table('activity_types',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('activity_details',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_parameter_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name='activity_details_ibfk_1'),
    sa.ForeignKeyConstraint(['activity_parameter_id'], ['activity_parameters.id'], name='activity_details_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('activity_parameters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('activities',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('activity_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], name='activities_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('candidate_education')
    op.drop_table('majors')
    # ### end Alembic commands ###
