"""updatetablecv3

Revision ID: e06f01aec0ea
Revises: 855cea9348ca
Create Date: 2020-12-26 18:22:58.143392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06f01aec0ea'
down_revision = '6efeb46c4889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('educations', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('experiences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'experiences')
    op.drop_column('resumes', 'educations')
    # ### end Alembic commands ###
