"""add_domain_skills_for_jp

Revision ID: f69d4e7d7d30
Revises: a4a2de6c22d9
Create Date: 2021-01-26 01:07:33.003108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69d4e7d7d30'
down_revision = 'a4a2de6c22d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('domain_skills', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'domain_skills')
    # ### end Alembic commands ###
