"""updateResumeModel

Revision ID: fda51c3f062d
Revises: c5dfd805205e
Create Date: 2020-12-27 22:11:33.822973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda51c3f062d'
down_revision = 'c5dfd805205e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('resume_file_extension', sa.String(length=10), nullable=False))
    op.add_column('resumes', sa.Column('resume_filename', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'resume_filename')
    op.drop_column('resumes', 'resume_file_extension')
    # ### end Alembic commands ###
